### ISSUE TITLE
What do you want to be different from minbrowser?

### ISSUE THREAD

**Issue by code-hunger** [doreminiature/miniature#2]
According to a presentation I watched one of the main goals of the project is to make the browser easier to use with many tabs.
This is already largely accomplished by the base of this repo (https://github.com/minbrowser/min) which I've been using quite a lot recently.

How does your project differ from minbrowser? What do you dislike about minbrowser, how do you want to extend it? I.e. why did you start a new project based on min?

**Comment by doreminiature** [comment]
Greets. Basically the goal of the project is to solve information overload dilemma. From what I saw observing regular people, they tend to open many tabs and afraid to close them. So list of tabs for them is like task list. And people tend to procrastinate, thus users with 50+ opened tabs. And regular users usually don't use bookmarks too.

1). First of all I see problem with tab mess when having many tabs opened, and I solve it with adding "collection tabs" for organization sake.
Collection tabs is also solution to upgrade bookmarks mechanism we have since mosaic browser (1993). Also I upgrade history mechanism.

2). Tab bar. I apply Miller's law (7 plus/minus 2) and typographic grid to make things polished and easy on the eye.
Tab bar adapts on whatever number of tabs you want there (actually up to 60 tabs per collection on fullHD display), we have a slider to control amount of tabs you watn to be visible per collection.
[tab bar: chrome vs miniature](https://i.imgur.com/ltkaa69.png)

3). Fast preview on tab hover. So each tab you have opened saves a screenshot webpage. This way you can use it andpreview the tabs you have very quickly and without waiting tab to load if you just started the browser. So imagine hundreds of tabs avail. on the first browser start and even if you are offline you can preview pages, after all you have every URL page you visited screenshoted (and updated from time to time).

4). Overview panel. Where you have overview of all your collections and tabs opened. With fast preview too, so hovering over list of tabs gives you quick preview (screenshots).

5). Predefined collections to choose from. Too hint people with great stuff, best pages on the collection subject. Also I would like to make this collections community editable.

Excuse for my english.

Regards.

**Comment by code-hunger** [comment]
All this seems quite appealing and is something that will definitely be useful if done right. I have some problems in building it though; I'm going to open another issue about that.
ps. Your English is perfectly understandable, don't worry about it :)

**Comment by doreminiature** [comment]
Try without uglification.
grunt.registerTask('linuxBuild', ['concat:browser',  'concat:webview', , 'concat:main', 'electron:linuxBuild', 'electron-installer-debian:linux32', 'electron-installer-debian:linux64'])

As for readme, yep my bad,.
